FROM golang:1.27-alpine@sha256:f92b6ef800e499660581efdabdf25d9d817a9d124eaf900924f0504e7e27e12d
WORKDIR /src
RUN apk update && apk add --no-cache \
    smartmontools dosfstools parted util-linux e2fsprogs hdparm \
    git make
RUN go install github.com/air-verse/air@latest
EXPOSE 8181
CMD ["air", "-c", ".air.toml"]
