FROM golang:1.26-alpine@sha256:8ac98ca534ac3f51e1f420a1dd2c15e74c75cfa0f23f3ad27eb5d7236c349a0c
WORKDIR /src
RUN apk update && apk add --no-cache \
    smartmontools dosfstools parted util-linux e2fsprogs hdparm \
    git make
RUN go install github.com/air-verse/air@latest
EXPOSE 8181
CMD ["air", "-c", ".air.toml"]
